#!/bin/bash
# deploy.sh — Sync modified sources to the DragonFlyBSD VM and build.
#
# Usage: ./deploy.sh [sync|build|install|tests|all]
#   sync    — Apply the overlay to /usr/src on the VM (bin/apply-overlay)
#   build   — Build hammer2.ko + newfs_hammer2 + hammer2 on the VM
#   install — quickkernel + reinstallkernel (loader-compatible hammer2.ko)
#             and install newfs_hammer2/hammer2; reboot or reload after
#   tests   — Sync test scripts to /root/hammer2-tests/ on the VM
#   all     — sync + build + install + tests (default)
#
# Environment:
#   KERNCONF  — kernel config on the VM (default H2DEV, generated by sync)
#   DFLY_HOST — override with a plain SSH host alias (default: the harness's
#               own identity from vmenv.sh, which needs no ~/.ssh/config and
#               therefore also works inside the claude-box sandbox)

set -e

DIR="$(cd "$(dirname "$0")" && pwd)"

VM_ROOT="$DIR"
. "$DIR/vmenv.sh"
if [ -n "${DFLY_HOST:-}" ]; then
    VM="$DFLY_HOST"
    VM_SSH_OPTS=""
    VM_SCP_OPTS=""
else
    VM="$VM_TARGET"
fi

# The guest runs DragonFly master built from /usr/src (the overlay's base)
# with KERNCONF=H2DEV: X86_64_GENERIC minus `options HAMMER2`, so hammer2
# is a module and `reload` can swap it without a reboot.
KERNCONF="${KERNCONF:-H2DEV}"

do_sync() {
    # Same mapping as a local bin/apply-overlay run: ship src/ and the
    # script, and let it place the files and patch sys/conf/files and
    # sbin/hammer2/Makefile on the guest.
    echo "==> Applying overlay to /usr/src (bin/apply-overlay)"
    ssh $VM_SSH_OPTS "$VM" "rm -rf /root/h2overlay; mkdir -p /root/h2overlay"
    tar -C "$DIR" -cf - bin/apply-overlay src/sys src/sbin |
        ssh $VM_SSH_OPTS "$VM" tar -xf - -C /root/h2overlay
    ssh $VM_SSH_OPTS "$VM" sh <<'ENDSSH'
set -e
sh /root/h2overlay/bin/apply-overlay /usr/src
cd /usr/src && git status --short sys sbin
ENDSSH

    echo "==> Ensuring /usr/src/sys/config/$KERNCONF"
    ssh $VM_SSH_OPTS "$VM" sh <<ENDSSH
set -e
cd /usr/src/sys/config
if [ "$KERNCONF" = H2DEV ]; then
    sed -e 's/^ident[[:space:]].*/ident		H2DEV/' \
        -e '/^options[[:space:]]*HAMMER2[[:space:]]/d' X86_64_GENERIC > H2DEV.new
    if cmp -s H2DEV.new H2DEV; then rm H2DEV.new; else mv H2DEV.new H2DEV; echo "    regenerated H2DEV"; fi
fi
ENDSSH
}

do_build() {
    echo "==> Building on VM..."
    ssh $VM_SSH_OPTS "$VM" sh <<'ENDSSH'
set -e
# Fast KMOD build: produces /usr/src/sys/vfs/hammer2/hammer2.ko in
# seconds.  This .ko loads fine via kldload at runtime; it just isn't
# loadable via /boot/loader at boot (that needs the kernel-tree
# variant from `make installkernel`, which deploy.sh install copies).
# For the inner edit-test loop, KMOD + kldload is the right path.
echo "--- hammer2.ko (KMOD, runtime-loadable) ---"
cd /usr/src/sys/vfs/hammer2
make

echo "--- newfs_hammer2 ---"
cd /usr/src/sbin/newfs_hammer2
make

echo "--- hammer2 utility ---"
cd /usr/src/sbin/hammer2
make

echo "--- Build complete ---"
ENDSSH
}

do_reload() {
    echo "==> Live-reloading hammer2.ko on VM..."
    ssh $VM_SSH_OPTS "$VM" sh <<'ENDSSH'
set -e
# Drop the running hammer2 and load the freshly-built KMOD .ko in
# place.  Requires no hammer2 filesystem to be mounted; `mount` is
# checked first and a hammer2 mount aborts the reload.
if mount | grep -q hammer2; then
    echo "    ERROR: a hammer2 filesystem is mounted — unmount first or reboot."
    mount | grep hammer2
    exit 1
fi
# Drop any hammer2 .ko by id (handles modules loaded under non-standard
# names — e.g. /tmp/kmod_hammer2.ko shows up in kldstat as kmod_hammer2).
kldstat | awk '/hammer2/ { print $1 }' | while read id; do
    [ -n "$id" ] && kldunload -i "$id" 2>/dev/null || true
done
kldload /usr/src/sys/vfs/hammer2/hammer2.ko
kldstat | grep hammer2
echo "    sysctl probe:"
sysctl vfs.hammer2.inject_eio_disk_mask 2>/dev/null || echo "      (sysctl absent)"
# Userspace binaries need to be on PATH for the test suite; cp here so
# `fast` matches what `install` does for these (kernel-tree .ko aside).
install -m 755 /usr/src/sbin/newfs_hammer2/newfs_hammer2 /sbin/newfs_hammer2
install -m 755 /usr/src/sbin/hammer2/hammer2 /sbin/hammer2
ENDSSH
}

do_install() {
    echo "==> Installing on VM (KERNCONF=$KERNCONF)..."
    ssh $VM_SSH_OPTS "$VM" sh <<ENDSSH
set -e
# The loader rejects the KMOD .ko from do_build ("file has no contents");
# it needs the kernel-tree module.  quickkernel rebuilds the kernel and
# modules in the existing /usr/obj tree (only hammer2 has changed), and
# reinstallkernel replaces /boot/kernel without touching kernel.old.
cd /usr/src
if [ ! -d /usr/obj/usr/src/sys/$KERNCONF ]; then
    echo "    ERROR: no /usr/obj/usr/src/sys/$KERNCONF; run"
    echo "           'make -j2 KERNCONF=$KERNCONF buildkernel' first."
    exit 1
fi
make -j2 KERNCONF=$KERNCONF quickkernel > /var/tmp/quickkernel.log 2>&1 ||
    { tail -30 /var/tmp/quickkernel.log; exit 1; }
make KERNCONF=$KERNCONF reinstallkernel > /var/tmp/reinstallkernel.log 2>&1 ||
    { tail -30 /var/tmp/reinstallkernel.log; exit 1; }
ls -l /boot/kernel/hammer2.ko
install -m 755 /usr/src/sbin/newfs_hammer2/newfs_hammer2 /sbin/newfs_hammer2
install -m 755 /usr/src/sbin/hammer2/hammer2 /sbin/hammer2
echo "--- Install complete ---"
echo "    NOTE: reboot (or ./deploy.sh reload) to activate the new hammer2.ko"
ENDSSH
}

do_tests() {
    echo "==> Syncing test scripts -> /root/hammer2-tests/"
    ssh $VM_SSH_OPTS "$VM" mkdir -p /root/hammer2-tests
    # Use tar to preserve directory structure (rsync may not be on DragonFlyBSD)
    tar -C "$DIR" -cf - tests | ssh $VM_SSH_OPTS "$VM" tar -xf - -C /root/hammer2-tests --strip-components=1
    echo "    Tests synced to /root/hammer2-tests/"

    echo "==> Syncing diagnostic tools -> /root/h2diag/"
    ssh $VM_SSH_OPTS "$VM" mkdir -p /root/h2diag
    tar -C "$DIR/src" -cf - diag | ssh $VM_SSH_OPTS "$VM" tar -xf - -C /root/h2diag --strip-components=1
    echo "    Diagnostics synced to /root/h2diag/"
}

ACTION="${1:-all}"

case "$ACTION" in
    sync)    do_sync ;;
    build)   do_build ;;
    install) do_install ;;
    reload)  do_reload ;;
    tests)   do_tests ;;
    fast)
        do_sync
        do_build
        do_reload
        do_tests
        ;;
    all)
        do_sync
        do_build
        do_install
        do_tests
        ;;
    *)
        echo "Usage: $0 [sync|build|install|reload|tests|fast|all]"
        echo ""
        echo "  fast = sync + build + reload + tests"
        echo "         (no reboot — KMOD .ko + kldload; requires no"
        echo "         hammer2 fs mounted)"
        echo "  all  = sync + build + install + tests"
        echo "         (install needs a prior buildkernel of \$KERNCONF;"
        echo "         reboot or reload to activate the module)"
        exit 1
        ;;
esac
